"""Fixing user table structure change nullable value

Revision ID: bc7df57c9ab9
Revises: bb9a759ee3fd
Create Date: 2023-10-27 09:12:59.111263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc7df57c9ab9'
down_revision = 'bb9a759ee3fd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
