"""The last war

Revision ID: b4e1111f3aaf
Revises: bc7df57c9ab9
Create Date: 2023-10-27 09:27:12.021319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4e1111f3aaf'
down_revision = 'bc7df57c9ab9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
