"""Fixing user table structure

Revision ID: bb9a759ee3fd
Revises: 9748a75ebd14
Create Date: 2023-10-27 07:18:49.086677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb9a759ee3fd'
down_revision = '9748a75ebd14'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.TEXT(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    op.alter_column('user', 'role',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
